language: python
sudo: false
dist: trusty

git:
  depth: 10

python:
  - "2.7"

services:
  - elasticsearch
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  chrome: stable

cache:
  pip: true
  directories:
    - node_modules
    # App's may have their own node_modules directory and should be listed here
    # in the format cfgov/unprocessed/apps/[namespace]/node_modules
    # If they are not listed here the caching mechanism will falsely see the
    # main node_modules directory as being cached and never run npm install,
    # which also installs app's node_modules.
    - cfgov/unprocessed/apps/owning-a-home/node_modules
    - cfgov/unprocessed/apps/regulations3k/node_modules
    - cfgov/unprocessed/apps/analytics-gtm/node_modules

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - ./travis_install.sh

branches:
  only:
    - master
    - elasticsearch-tests

before_script:
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';"

script:
  - ./travis_run.sh

env:
  global:
    - DJANGO_SETTINGS_MODULE=cfgov.settings.test
    - DJANGO_STAGING_HOSTNAME=content.localhost
    - COVERALLS_PARALLEL=true
    - PGPORT=5433
    - ES_VERSION=2.3.5 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz

jobs:
  fast_finish: true
  include:
    - stage: Run Tests
      env: RUNTEST=frontend
    - env:
        - RUNTEST=backend
        - TEST_RUNNER=cfgov.test.StdoutCapturingTestRunner
    - stage: Docs Deploy
      if: tag IS present
      env: RUNTEST=docs
      deploy:
        provider: pages
        local_dir: site
        skip-cleanup: true
        github_token: $GITHUB_TOKEN
